In [7]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

HEADERS = {
            'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Mobile Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
            'Accept-Language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3',
            'Accept-Encoding': 'gzip, deflate, br',
            'DNT': '1',
            'Connection': 'keep-alive',
        }

metro_district = ['Печерский', 'Шевченковский']
district_dict = {'Печерский': 2.87, 'Шевченковский': 1.74, 'Голосеевский': 1.53, 'Подольский': 1.29, 'Оболонский': 1.22, 'Соломенский': 1.19, 'Днепровский': 1.19, 'Святошинский': 1.18, 'Дарницкий': 1.12, 'Деснянский': 1.00}

district_list = []
area_list = []
rooms_list = []
floor_list = []
near_metro_list = []
gk_list = []
adress_list = []
price_list = []




for page in range (1, 198):
    SITE = f'https://rieltor.ua/ru/flats-rent/?price_min=4600&price_max=300000&page={page}'

    r = requests.get(SITE, headers=HEADERS)

    if r.status_code == 200:
        soup = BeautifulSoup(r.text, 'lxml')


        for el in soup.find_all('div', class_='catalog-item'):
            adress = el.find_all('a')[1].text.split()
            str_adres = ' '.join(adress)
            try:
                adress_list.append(str_adres)# адрес (район)
            except ValueError as e:
                adress_list.append(None)
            try:
                district = el.find_all('a')[1].text.split()[-2]
                number_distr = district_dict.get(district)
                district_list.append(number_distr)# number район
            except IndexError as e:
                district_list.append(None)
            metro = el.find_all('a')[2].text.split()
            try:
                if '(M)' in metro:
                    near_metro_list.append(1)
                else:
                    if district in metro_district:
                        near_metro_list.append(1)
                    else:                        
                        if 'метро' in el.find('p', class_='catalog-item_info-item-row catalog-item_info-description').text:
                            near_metro_list.append(2)                  
                        else:
                            near_metro_list.append(3)
                    
            except AttributeError as e:
                near_metro_list.append(None)


            price = el.find('strong', class_='catalog-item__price').text # цена
            if '$/мес' in price:
                price_list.append(int(price.rstrip('$/мес').replace(' ', '')) * 27.5)
            else:
                price_list.append(int(price.rstrip('грн/мес').replace(' ', ''))) 
            try:
                rooms = int(el.find('div', class_='catalog-item_info-item-row').text.split()[0])
                rooms_list.append(rooms)#комнаты
            except ValueError as e:
                rooms_list.append(None)

            try:
                floor = int(el.find('div', class_='catalog-item_info-item-row').text.split()[2])
                floor_list.append(floor)   # этаж
            except ValueError as e:
                floor_list.append(None)
            try:    
                area = float(el.find('div', class_='catalog-item_info-item-row').text.split()[-6])
                area_list.append(area)# площадь
            except ValueError as e:
                area_list.append(None)
            try:
                gk = el.find('p', class_='catalog-item_info-item-row catalog-item_info-description').text
                if 'ЖК' in gk:
                    #print(int(1))
                    gk_list.append(1)
                elif 'комплекс%' in gk:
                    gk_list.append(1)
                else:
                    #print(int(0))
                    gk_list.append(0)
            except AttributeError as e:
                    gk = None
                    #print(int(0))
                    gk_list.append(0)


    dfr = pd.DataFrame({'district': district_list, 'metro': near_metro_list, 'area': area_list, 'rooms': rooms_list, 'floor': floor_list, 'gk': gk_list, 'price': price_list, 'adress': adress_list})

            
dfr

,district,metro,area,rooms,floor,gk,price,adress
0,1.74,1.0,50.0,2.0,11.0,1,27500.0,"Златоустовская ул., 30, Шевченковский р-н"
1,2.87,1.0,70.0,2.0,18.0,1,33000.0,"Евгения Коновальца ул. (Щорса), 44а, Печерский..."
2,2.87,1.0,96.0,2.0,10.0,0,35750.0,"Михаила Омеляновича-Павленка ул. (Суворова), П..."
3,NaN,3.0,34.0,1.0,8.0,0,5800.0,"Шолом-Алейхема ул., 15"
4,2.87,1.0,127.0,3.0,4.0,0,20625.0,"Е. Коновальца ул. (Щорса), 32-г, Печерский р-н"
...,...,...,...,...,...,...,...,...
3935,1.29,3.0,27.0,1.0,1.0,0,6000.0,"Галицкая ул., Подольский р-н"
3936,1.18,3.0,45.0,2.0,4.0,0,6996.0,"Ромена Роллана, Святошинский р-н"
3937,NaN,3.0,65.0,3.0,1.0,0,9000.0,Терещенко Николая ул.
3938,1.12,3.0,67.0,2.0,9.0,0,12500.0,"Драгоманова ул., Дарницкий р-н"
3939,1.12,2.0,97.0,3.0,17.0,0,16899.0,"Срибнокильская ул., Дарницкий р-н"

In [9]:
dfr1 = dfr.dropna()
dfr1.isnull().sum()

district    0
metro       0
area        0
rooms       0
floor       0
gk          0
price       0
adress      0
dtype: int64

In [10]:
dfr1.to_csv('rent5.csv', encoding='utf-8', index=False)